services:
    cdwv.cron_configuration:
        class: CodeWave\CronosDatabaseDumperBundle\Cron\CronConfiguration

    cdwv.cron:
        class: MyBuilder\Cronos\Formatter\Cron

    cdwv.dumper_command_builder:
        class:  CodeWave\CronosDatabaseDumperBundle\Dumper\DumperCommandBuilder
        arguments:
            - "@cdwv.cron_configuration"
            - "%kernel.root_dir%"

    cdwv.cronos.cron_manipulator:
        class: MyBuilder\Cronos\Updater\CommandCronManipulator
        arguments:
            - "@cdwv.cronos.process_runner"
            - "@cdwv.cronos.filesystem"
        public: false

    cdwv.cronos.process_runner:
         class: MyBuilder\Cronos\Updater\SymfonyProcessRunner
         public: false

    cdwv.cronos.filesystem:
         class: MyBuilder\Cronos\Updater\SymfonyFileSystem
         public: false

    cdwv.cronos_bundle.cron_process_updater:
        class: MyBuilder\Cronos\Updater\CronUpdater
        arguments:
            - "@cdwv.cronos.cron_manipulator"

    cdwv.cron_builder:
        class: CodeWave\CronosDatabaseDumperBundle\Cron\CronJobBuilder
        arguments:
            - "@cdwv.cron"
            - "@cdwv.cron_configuration"